label stuck:
    K "You said it's a 'time loop', so we're like stuck, and the time restart everyday ?"
    S "Not necessarily everyday, but yeah indeed and no one remembers anything; and everything that happened kinda... didn't happen."
    K "Any idea what's causing this ?"
    R "I̷t̶'̴s̴ ̶t̴h̷a̵t̸ ̵f̷u̶c̸k̷i̵n̷g̴ ̵b̵l̶u̶e̶ ̴b̵i̶t̴c̵h̸"
    S "*sigh* that's embarassing, but after all these years, I have no idea. Purgatory ? Weird coma ? Alternate world ? Hell if I know ..."
    K "You've been stuck fo years ??"
    S "Yeah, but you get used to it, don't worry."
    K "I'm not sure I wanna ..."
    K "That sound terrifying, living the same things over and over again ? That'd be a literal hell !"
    S "Heh, my actions aving no consequences is kinda ~cool if you ask me."
    K "Nina..."
    K "There something else I'd like to know-"
    S "When we're home !"
    S "I don't wanna talk about time and loopall night, i haven't seen you in years ! I wanna catch up !"
    K "*sigh* You're right... Sorry,"
    scene black
    show rem
    pause 0.5
    R "I̴ ̴s̷e̸e̷ ̶e̶v̶e̸r̵y̶t̷h̶i̸n̷g̵ ̷y̶o̷u̶ ̸k̶n̶o̷w̸ ̷?̵"   
    R "I̵ ̶k̸n̶o̸w̶ ̶y̸o̸u̶ ̴c̴a̶n̵ ̸h̶e̷a̷r̵ ̸m̶e̸"
    R "I̶ ̴k̴n̷o̵w̴ ̸y̶o̷u̶ ̸c̷a̴n̸'̴t̶ ̷a̸n̷s̷w̵e̶r̸ ̴m̶e̶.̵ ̸"
    R "T̵h̵e̴ ̸c̷h̸o̸i̷c̷e̸ ̵w̷i̸n̶d̵o̵w̷ ̶i̸s̸n̵'̸t̷ ̶a̶p̷p̶e̵a̷r̷i̴n̵g̸"
    R "Y̷o̵u̵ ̶a̶c̶t̷u̷a̶l̴l̷y̶ ̷t̸r̶i̶e̸d̴ ̸t̴o̶ ̷s̶a̶v̴e̷ ̵h̸e̸r̶ ̷"
    R "W̷h̸a̸t̶ ̶a̵ ̴p̸a̶t̸h̶e̶t̸i̸c̶ ̶a̷t̷t̴e̴m̸p̷t̷ ̵a̸t̴ ̷t̴h̶a̴t̵ ̷l̵o̸l̷"
    R "B̴u̷t̵ ̸I̷ ̵g̴u̸e̴s̸s̵ ̶t̵h̵a̵t̶'̴s̷ ̶e̶a̴s̸y̵ ̵r̴i̵s̶k̶i̵n̴g̶ ̵e̵v̵e̷r̸y̵t̵h̷i̷n̶g̴,̶ ̵w̸h̷e̸n̷ ̷i̵t̸'̸s̷ ̷n̸o̸t̶ ̶y̴o̷u̷r̷ ̵o̸w̸n̷ ̴b̵o̵d̸y̶ ̴o̷n̵ ̵t̷h̸e̴ ̵l̶i̷n̸e̵?̴"
    R "̸I̴'̶l̸l̴ ̶j̶u̵s̷t̷ ̴t̶e̴l̸l̷ ̸y̷o̷u̷ ̵o̷n̴e̵ ̵t̵h̸i̵n̷g̵.̵ ̵"
    R "I̴f̸ ̷y̵o̴u̸ ̵k̸n̵o̸w̶ ̶w̸h̵a̷t̶'̵s̵ ̸g̷o̵o̸d̸ ̸f̸o̸r̴ ̴y̵o̷u̵"
    R "F̵U̸C̴K̵ ̴O̴F̴F̴"
    R "T̸h̶i̸s̵ ̴i̷s̸ ̶n̵o̸t̶ ̶y̶o̸u̷r̸ ̴w̶o̸r̸l̸d̴.̵"
    return
